name: Build and push Docker image to Heroku
description: Build Docker image for server, swaps tracker and maker mock and push to Heroku Container Registry

inputs:
  heroku_api_key:
    description: "Heroku API key"
    required: true
  heroku_app_name:
    description: "Heroku app name"
    required: true
  heroku_app_type:
    description: "Heroku app type"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Heroku Container Registry
      shell: bash
      run: heroku container:login
      env:
        HEROKU_API_KEY: ${{ inputs.heroku_api_key }}

    - name: Build Docker Image for Server
      shell: bash
      run: |
        if [ "$HEROKU_APP_TYPE" == "web" ]; then
          APP_PATH="./cmd/order-book"
        elif [ "$HEROKU_APP_TYPE" == "worker" ]; then
          APP_PATH="./cmd/pending-swaps-tracker"
        else
          echo "Invalid Heroku app type specified"
          exit 1
        fi
        docker build --build-arg APP_PATH=$APP_PATH -t registry.heroku.com/$HEROKU_APP_NAME/$HEROKU_APP_TYPE -f cmd/order-book.Dockerfile .
      env:
        HEROKU_APP_NAME: ${{ inputs.heroku_app_name }}
        HEROKU_APP_TYPE: ${{ inputs.heroku_app_type }}

    - name: Push Docker Image for Server to Registry
      shell: bash
      run: docker push registry.heroku.com/$HEROKU_APP_NAME/$HEROKU_APP_TYPE
      env:
        HEROKU_API_KEY: ${{ inputs.heroku_api_key }}
        HEROKU_APP_NAME: ${{ inputs.heroku_app_name }}
        HEROKU_APP_TYPE: ${{ inputs.heroku_app_type }}
