name: Build and push Docker image to Heroku
description: Build Docker image for server, swaps tracker and maker mock and push to Heroku Container Registry

inputs:
  heroku_api_key:
    description: "Heroku API key"
    required: true
  heroku_app_name:
    description: "Heroku app name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Heroku Container Registry
      shell: bash
      run: heroku container:login
      env:
        HEROKU_API_KEY: ${{ inputs.heroku_api_key }}

    - name: Build Docker Image for Server
      shell: bash
      run: |
        docker build --build-arg APP_PATH=./cmd/order-book -t registry.heroku.com/$HEROKU_APP_NAME/web -f cmd/order-book.Dockerfile .
      env:
        HEROKU_APP_NAME: ${{ inputs.heroku_app_name }}

    - name: Push Docker Image for Server to Registry
      shell: bash
      run: docker push registry.heroku.com/$HEROKU_APP_NAME/web
      env:
        HEROKU_API_KEY: ${{ inputs.heroku_api_key }}
        HEROKU_APP_NAME: ${{ inputs.heroku_app_name }}
