version: "3.8"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "80:8080"
    environment:
      - REDIS_URL=redis://db:6379/0
      - PORT=8080
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          files:
            - ./**/*.go
            - ./go.mod
            - ./go.sum

  db:
    image: redis:7.2.1-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - db:/data
volumes:
  db:
    driver: local
