# NOTE: This pipeline is deprecated and will be removed in the near future

name: Build and Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Build Docker Image for Server
        run: |
          docker build --build-arg APP_PATH=./cmd/order-book -t registry.heroku.com/order-book-server/web -f cmd/order-book.Dockerfile .

      - name: Push Docker Image for Server to Registry
        run: docker push registry.heroku.com/order-book-server/web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  build-swapstracker:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Build Docker Image for Swaps Tracker
        run: |
          docker build --build-arg APP_PATH=./cmd/pending-swaps-tracker -t registry.heroku.com/order-book-pending-swaps-track/worker -f cmd/order-book.Dockerfile .

      - name: Push Docker Image for Swaps Tracker to Registry
        run: docker push registry.heroku.com/order-book-pending-swaps-track/worker
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  deploy-nonprod:
    runs-on: ubuntu-latest
    needs: [build-server, build-swapstracker]
    environment: nonprod

    steps:
      - name: Login to Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Pull and Release Image for Server Nonprod
        run: |
          heroku container:release web --app order-book-server
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Pull and Release Image for Swaps Tracker Nonprod
        run: |
          heroku container:release worker --app order-book-pending-swaps-track
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-nonprod
    environment: prod

    steps:
      - name: Login to Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Pull and Release Image for Server Prod
        run: |
          docker pull registry.heroku.com/order-book-server/web
          docker tag registry.heroku.com/order-book-server/web registry.heroku.com/order-book-server-prod/web
          docker push registry.heroku.com/order-book-server-prod/web
          heroku container:release web --app order-book-server-prod
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Pull and Release Image for Swaps Tracker Prod
        run: |
          docker pull registry.heroku.com/order-book-pending-swaps-track/worker
          docker tag registry.heroku.com/order-book-pending-swaps-track/worker registry.heroku.com/order-book-swaps-track-prod/worker
          docker push registry.heroku.com/order-book-swaps-track-prod/worker
          heroku container:release worker --app order-book-swaps-track-prod
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
