name: End-to-End Tests
on:
  pull_request:
    branches: [main]

jobs:
  build-and-run-e2e-tests:
    runs-on: ubuntu-latest

    env:
      REDIS_URL: redis://localhost:6379/0
      PUBLIC_KEY: "0x6a04ab98d9e4774ad806e302dddeb63bea16b5cb5f223ee77478e861bb583eb336b6fbcb60b5b3d4f1551ac45e5ffc4936466e7d98f6c7c0ec736539f74691a6"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install -r e2e/tests/requirements.txt

      - uses: isbang/compose-action@v1.5.1
        name: Start services
        with:
          up-flags: -d --wait
        env:
          RPC_URL: ${{ secrets.RPC_URL }}

      - name: Wait for services to be ready
        run: |
          sleep 10

      - name: Set up Market Maker User
        run: |
          ./scripts/create-user/create-user-x86_64

      - name: Set API key as env var
        run: |
          echo "API_KEY=$(cat api_key.txt)" >> $GITHUB_ENV

      - name: Run market maker endpoint tests
        run: |
          cd e2e/tests && pytest -v -s --showlocals -rA

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: Test Reports
          path: e2e/tests/results.xml
